/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

//cliente y equipo son del modelo
import clases.Cliente;
import clases.Equipo;
import clases.EquipoCliente;
import dao.ClienteDAO;
import dao.EquipoDAO;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class AsignarEquiposClienteFrm extends javax.swing.JFrame {

	/**
	 * Creates new form AsignarEquiposClienteFrm
	 */
	public AsignarEquiposClienteFrm() {
		initComponents();
		creaCmbClientes();
		pnlEquipos.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		cmbClientes = new javax.swing.JComboBox<>();
		btnEquipos = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		btnAsignar = new javax.swing.JButton();
		pnlEquipos = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblEquipos = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

		btnEquipos.setText("Ver Equipos");
		btnEquipos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEquiposActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(29, 29, 29)
						.addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
						.addComponent(btnEquipos).addGap(36, 36, 36)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnEquipos))
						.addContainerGap(39, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("Asignar Equipos");

		btnAsignar.setText("Asignar Equipo");
		btnAsignar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAsignarActionPerformed(evt);
			}
		});

		pnlEquipos.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipo"));

		tblEquipos
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblEquipos);

		javax.swing.GroupLayout pnlEquiposLayout = new javax.swing.GroupLayout(pnlEquipos);
		pnlEquipos.setLayout(pnlEquiposLayout);
		pnlEquiposLayout
				.setHorizontalGroup(pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								pnlEquiposLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(23, 23, 23)));
		pnlEquiposLayout
				.setVerticalGroup(
						pnlEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlEquiposLayout.createSequentialGroup().addContainerGap()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(23, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(32, 32, 32).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(btnAsignar)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pnlEquipos, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addContainerGap(26, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel1).addGap(29, 29, 29)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(pnlEquipos, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnAsignar).addGap(54, 54, 54)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEquiposActionPerformed
		creaTablaEquipos();
	}// GEN-LAST:event_btnEquiposActionPerformed

	private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAsignarActionPerformed
		asignarEquipos();
	}// GEN-LAST:event_btnAsignarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AsignarEquiposClienteFrm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AsignarEquiposClienteFrm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AsignarEquiposClienteFrm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AsignarEquiposClienteFrm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AsignarEquiposClienteFrm().setVisible(true);
			}
		});
	}

	private void creaCmbClientes() {
		ClienteDAO clienteDAO = new ClienteDAO();
		LinkedList<Cliente> lista = clienteDAO.listaClientes();
		Cliente clienteVacio = new Cliente(null, "Selecciona un Cliente", "", "");
		cmbClientes.addItem(clienteVacio);
		for (int i = 0; i < lista.size(); i++) {
			cmbClientes.addItem(lista.get(i));
		}
	}

	public void creaTablaEquipos() {

		pnlEquipos.setVisible(true);
		EquipoDAO equipoDAO = new EquipoDAO();
		LinkedList<Equipo> lista = equipoDAO.listaEquipos();
		Vector columnas = new Vector();
		columnas.add("Modelo");
		columnas.add("Color");
		columnas.add("Sistema Operativo");
		columnas.add("Precio");
		columnas.add("Fabricante");

		Vector filas = new Vector();
		Vector fila = new Vector();

		for (int i = 0; i < lista.size(); i++) {

			fila.add(lista.get(i).getModelo());
			fila.add(lista.get(i).getColor());
			fila.add(lista.get(i).getSistemaOperativo());
			fila.add(lista.get(i).getPrecio());
			fila.add(lista.get(i).getFabricante());

			filas.add(fila);
			fila = new Vector();
		}

		DefaultTableModel modelo = new DefaultTableModel(0, 0);
		modelo.setDataVector(filas, columnas);
		tblEquipos.setModel(modelo);
	}

	private void asignarEquipos() {
		Cliente cliente = (Cliente) cmbClientes.getSelectedItem();

		if (cliente.getId() != null) {
			int fila = tblEquipos.getSelectedRow();
			if (fila == -1) {
				JOptionPane.showMessageDialog(this, "Selecciona un Equipo", "Error!!!", JOptionPane.ERROR_MESSAGE);
			} else {
				String modelo = (String) tblEquipos.getValueAt(fila, 0);
				String color = (String) tblEquipos.getValueAt(fila, 1);
				Date myDate = new Date();
				String fecha = new SimpleDateFormat("yyyy-MM-dd").format(myDate);
				EquipoDAO equipoDAO = new EquipoDAO();
				EquipoCliente ec = equipoDAO.buscarEquipo(modelo, color); // se recibe el objeto incompleto
				ec.setIdCliente(cliente.getId()); // acompletado del objeto
				ec.setFecha(fecha); // acompletado del objeto

				if (equipoDAO.asignar(ec)) {
					JOptionPane.showMessageDialog(this, "Se agrego el equipo " + modelo + " con exito!!!",
							"Agregación de Equipos", JOptionPane.INFORMATION_MESSAGE);
				}

			}
		} else {
			JOptionPane.showMessageDialog(this, "Selecciona un Cliente", "Error!!!", JOptionPane.ERROR_MESSAGE);
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAsignar;
	private javax.swing.JButton btnEquipos;
	private javax.swing.JComboBox<Cliente> cmbClientes;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JPanel pnlEquipos;
	private javax.swing.JTable tblEquipos;
	// End of variables declaration//GEN-END:variables
}